version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"     # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik-letsencrypt:/letsencrypt
    networks:
      - web

  mongodb:
    image: mongo:5
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    volumes:
      - mongo-data:/data/db

  lti-provider:
    build: .
    restart: unless-stopped
    environment:
      LTI_KEY: ${LTI_KEY}
      DB_HOST: mongodb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      PORT: 3000
    depends_on:
      - mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lti.rule=Host(`lti.csbasics.in`)"
      - "traefik.http.routers.lti.entrypoints=websecure"
      - "traefik.http.routers.lti.tls=true"
      - "traefik.http.routers.lti.tls.certresolver=letsencrypt"
      - "traefik.http.services.lti.loadbalancer.server.port=3000"
      
      # HTTP to HTTPS redirect
      - "traefik.http.routers.lti-http.rule=Host(`lti.csbasics.in`)"
      - "traefik.http.routers.lti-http.entrypoints=web"
      - "traefik.http.routers.lti-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - web

volumes:
  mongo-data:
  traefik-letsencrypt:

networks:
  web:
    external: false
